### ISSUE TITLE
Unable to lend out a book

### ISSUE THREAD

**Issue by te4-adrian-almetun-smeds** [itggot-TE4/Yabs#388]
### Description
When trying to lend out a book the backend return a `422 (Unprocessable Entity)` status code, and does not lend the book.

### Expected behavior
A book should be lended to the user.

## 🔬 To Reproduce
1. Go to `admin/loans`
3. Fill in the input fields
2. Click on 'LÅNA UT'
4. Observe error in console

### 🔥 Exception or error
```bash
# Backend

backend_1   | Started POST "/api/v1/loans" for 192.168.0.1 at 2020-12-09 19:31:08 +0000
backend_1   | Processing by Api::V1::LoansController#create as HTML
backend_1   |   Parameters: {"lent_by_id"=>REDACTED, "loaned_by_id"=>"REDACTED", "book_id"=>"1001", "loan"=>{"loaned_by_id"=>"REDACTED", "lent_by_id"=>REDACTED, "book_id"=>"1001"}}
backend_1   |   User Load (0.4ms)  SELECT "users".* FROM "users" WHERE "users"."uid" = ? LIMIT ?  [["uid", REDACTED], ["LIMIT", 1]]
backend_1   |   ↳ app/controllers/application_controller.rb:17:in `current_user'
backend_1   |   CACHE User Load (0.1ms)  SELECT "users".* FROM "users" WHERE "users"."uid" = ? LIMIT ?  [["uid", REDACTED], ["LIMIT", 1]]
backend_1   |   ↳ app/controllers/api/v1/loans_controller.rb:25:in `create'
backend_1   |   CACHE User Load (0.0ms)  SELECT "users".* FROM "users" WHERE "users"."uid" = ? LIMIT ?  [["uid", REDACTED], ["LIMIT", 1]]
backend_1   |   ↳ app/controllers/api/v1/loans_controller.rb:25:in `create'
backend_1   |    (2.3ms)  begin transaction
backend_1   |   ↳ app/controllers/api/v1/loans_controller.rb:25:in `create'
backend_1   |   Book Load (0.6ms)  SELECT "books".* FROM "books" WHERE "books"."barcode" = ? LIMIT ?  [["barcode", "1001"], ["LIMIT", 1]]
backend_1   |   ↳ app/controllers/api/v1/loans_controller.rb:25:in `create'
backend_1   |   Loan Exists? (0.9ms)  SELECT 1 AS one FROM "loans" WHERE "loans"."book_id" = ? LIMIT ?  [["book_id", "1001"], ["LIMIT", 1]]
backend_1   |   ↳ app/controllers/api/v1/loans_controller.rb:25:in `create'
backend_1   |    (2.1ms)  rollback transaction
backend_1   |   ↳ app/controllers/api/v1/loans_controller.rb:25:in `create'
backend_1   | Completed 422 Unprocessable Entity in 128ms (Views: 1.2ms | ActiveRecord: 7.2ms | Allocations: 14120)
```

**Comment by te4-adrian-almetun-smeds** [comment]
Probably associated with #406

**Comment by te4-adrian-almetun-smeds** [comment]
This has been resolved.
