### ISSUE TITLE
Rubocop in Husky pre-commit hook 

### ISSUE THREAD

**Issue by te4-adrian-almetun-smeds** [itggot-TE4/Yabs#629]
## ✨ Feature request
To enforce our code standard on the local client we should lint the code before pushing.
Add rubocop linting to husky pre-commit hook.

### 📜 Acceptance Criteria

- Add rubocop linting to husky pre-commit hook

### 💡 Additional context
Rubocop was introduced in #625

**Comment by te4-andre-skvarc** [comment]
Rubocop can be runed with ```docker-compose exec backend bundle exec rubocop```  But this is not possible with husky, it returns this ```the input device is not a TTY
husky > pre-commit hook failed (add --no-verify to bypass)```
But if you try to run it with just ```rubocop``` throws this error.  

```                                   
cannot load such file -- rubocop-rails
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/rubocop-1.2.0/lib/rubocop/config_loader_resolver.rb:17:in `block (2 levels) in resolve_requires'
/Library/Ruby/Gems/2.6.0/gems/rubocop-1.2.0/lib/rubocop/config_loader_resolver.rb:13:in `each'
/Library/Ruby/Gems/2.6.0/gems/rubocop-1.2.0/lib/rubocop/config_loader_resolver.rb:13:in `block in resolve_requires'
/Library/Ruby/Gems/2.6.0/gems/rubocop-1.2.0/lib/rubocop/config_loader_resolver.rb:12:in `tap'
/Library/Ruby/Gems/2.6.0/gems/rubocop-1.2.0/lib/rubocop/config_loader_resolver.rb:12:in `resolve_requires'
/Library/Ruby/Gems/2.6.0/gems/rubocop-1.2.0/lib/rubocop/config_loader.rb:43:in `load_file'
/Library/Ruby/Gems/2.6.0/gems/rubocop-1.2.0/lib/rubocop/config_loader.rb:104:in `configuration_from_file'
/Library/Ruby/Gems/2.6.0/gems/rubocop-1.2.0/lib/rubocop/config_store.rb:58:in `for_dir'
/Library/Ruby/Gems/2.6.0/gems/rubocop-1.2.0/lib/rubocop/config_store.rb:37:in `for_pwd'
/Library/Ruby/Gems/2.6.0/gems/rubocop-1.2.0/lib/rubocop/cli.rb:124:in `apply_default_formatter'
/Library/Ruby/Gems/2.6.0/gems/rubocop-1.2.0/lib/rubocop/cli.rb:40:in `run'
/Library/Ruby/Gems/2.6.0/gems/rubocop-1.2.0/exe/rubocop:13:in `block in <top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
/Library/Ruby/Gems/2.6.0/gems/rubocop-1.2.0/exe/rubocop:12:in `<top (required)>'
/usr/local/bin/rubocop:23:in `load'
/usr/local/bin/rubocop:23:in `<main>' ```

This problem rots down in that our mac's came with ruby already preinstalled and therefore it doesn't let us change some gems...

**Comment by ntijoh-daniel-berg** [comment]
This might be simple to fix now that everything runs in the container.
